### ISSUE TITLE
After Installing PageEdit, sigil displays most punctuation and numbers as Thai characters

### ISSUE THREAD

**Issue by NilocEsrom** [Sigil-Ebook/PageEdit#29] opened 2023-05-13 07:35 UTC
![Screenshot from 2023-05-13 17-30-16](https://github.com/Sigil-Ebook/PageEdit/assets/112829726/d7d28a3c-c528-4307-b333-9557fe33b3ed)

Not sure why this is happening, but after installing PageEdit, Sigil displays punctuation and numbers as Thai characters.
New xhtml file - Thai characters
If I export a LibreOffice document as epub, then open in Sigil - Thai characters
Copy and paste into Sigil - Thai characters

**Comment by dougmassay** [comment] 2023-05-13 11:28
There is no way that I can think of that PageEdit could affect how Sigil's Code View renders markup. Especially if you're using newly created content/epubs untouched by PageEdit.

It looks like you're using Windows, but what version? And what versions of Sigil PageEdit?

**Comment by kevinhendricks** [comment] 2023-05-13 12:33
Could this be Linux.  Some Linux distributions ship a Qt6 version of PageEdit and a Qt5 version of Sigil, not sure why?  Perhaps a conflict of some sort?

Perhaps one changes the a locale setting and makes Sigil think that file encoding is not utf-8 and instead some 8-bit encoding of some sort.

Quite strange.  I test with multiple Qt 5 and Qt 6 versions of Sigil and PageEdit with no problems?

Were both downloaded from our exact Releases website?  Or did you get them from somewhere else?

**Comment by NilocEsrom** [comment] 2023-05-14 09:21
Ah, yeah, sorry forgot to mention my OS, I'm using Linux Mint 20

I haven't changed anything on my system. I was working with some Thai text recently, but just copy and pasting.

I got PageEdit from  Github, but installed Sigil from the repository

**Comment by NilocEsrom** [comment] 2023-05-14 09:29
This happens with both the repo version and the flathub

**Comment by dougmassay** [comment] 2023-05-14 11:05
The Sigil version in the Mint 20 repos would be quite old (we don't really have any input in how the Flat pan version is constructed). I've run the Arch repo version of page edit (Qt6) with my own customs built version of Sigil (Qt5) for quite some time with no issues. I've never seen anything quite like a Code View with no angle brackets around the tags. What font are you using for Code View (which must be a mono space font, by the way) in Civilization preferences?

**Comment by dougmassay** [comment] 2023-05-14 11:06
Sorry. Autocorrect destroyed my attempt to type "Flatpak".

**Comment by kevinhendricks** [comment] 2023-05-14 13:13
And what do you mean you got the PageEdit version from github?  We have no linux release binaries on our github site.  Do you mean you built the latest PageEdit from source for Linux Mint 20?  What exact version of both are you using?

My guess is when you were "working with some Thai text recently" you either added a font that supports Thai or changed your locale setting.

**Comment by NilocEsrom** [comment] 2023-05-14 20:59
"The Sigil version in the Mint 20 repos would be quite old"
I tried getting the one on github, but i cant find any instructions to unpack it.

"What font are you using for Code View"
Which ever one is default.

"And what do you mean you got the PageEdit version from github? We have no linux release binaries on our github site."
Yes you do
https://github.com/Sigil-Ebook/PageEdit/releases
I unpacked the tar.gz as per instructions.


"you either added a font that supports Thai or changed your locale setting."
Hmm, I added a font. Odd how that could be the unerlying cause, but ill try removing it.
My locale is, and always had been, set to Australia.


"What exact version of both are you using?"
Sigil 1.1.0
PageEdit 1.9.2

**Comment by dougmassay** [comment] 2023-05-14 21:10
The tar.gz archive is not a binary release. It is the source code for that release. It cannot be "installed," it must be compiled. Saying you "installed" the github version was a bit confusing.

Same with Sigil. There are no binary installers provided for Linux in any of our Github releases for Sigil or PageEdit. Only source-code.

**Comment by NilocEsrom** [comment] 2023-05-14 22:23
Okay, I did the thing because I wanted to use Sigil to make ebooks. The thing was on GitHub, and I did it. 

Anyway, I removed the Thai font via my font manager and it seems to be back to normal now.

**Comment by kevinhendricks** [comment] 2023-05-14 23:15
Huh?  What thing on Github did you do?

So the issue was the font you installed and not related to installing PageEdit at all.

Closing this since not a bug.

**Closed by kevinhendricks** 2023-05-14 23:15 UTC
