### ISSUE TITLE
Introduse the Clip-Function as it is already avalable in Sigil itself

### ISSUE THREAD

**Issue by olsvse** [Sigil-Ebook/PageEdit#30] opened 2023-06-23 17:26 UTC
Hello,
I intend to switch from the old Sigil to the new one with PageEdsit as Editor.
In the combination from Sigil and Page-Edit shows as mostly working.
I'm German and my signs for a direct speech is not the "-Sign.
This signs are typicaly for a language. In German there are a combination of a lower-" and a upper-". 
In the old Sigil I could use as a workaround the clip-Function.
And normally the computer should be able to detect the used language-settings and do the correct signing. As an example it do LibreOffice.
So now I request to do the correct Signing automaticaly or introduce the clip-Function from Sigil also in Page-Edit.

Thanks.

**Comment by kevinhendricks** [comment] 2023-06-23 21:22
This is a new feature request.  As explained in the ReadMe here, new feature requests are not allowed in our github issues.  Instead they should be directed to our Sigil User's forum in www.mibileread.com so that other interested users can comment.

Closing this since not a bug/issue.

**Closed by kevinhendricks** 2023-06-23 21:22 UTC
