### ISSUE TITLE
PageEdit not for Mac OS 10.11

### ISSUE THREAD

**Issue by francwalter** [Sigil-Ebook/PageEdit#15] opened 2020-03-31 11:57 UTC
Hallo
is there any note to find an old version running on Mac OS 10.11?
I tried one after another older PageEdit versions down to 0.7.1 but none of them works on OS 10.11 on Mac.
So I guess this is similar than with Sigil, where I already just put [an issue for this problem](https://github.com/Sigil-Ebook/Sigil/issues/518).
Please put any note on the release page, when PageEdit stopped working on 10.11 or prior.
Thanks.
frank 
MacBook Pro from Mid 2009 with 10.11.6

**Comment by kevinhendricks** [comment] 2020-03-31 12:02
This is not a bug.  Closing this.  If you wanted to ask general questions you should ask on our MobileRead User forum page, not create bug reports

**Closed by kevinhendricks** 2020-03-31 12:02 UTC

**Comment by francwalter** [comment] 2020-03-31 12:39
In my opinion it is a missing information. Not a real bug, but something incomplete on this github project. You could put it on the wiki, this information though.

**Comment by dougmassay** [comment] 2020-03-31 12:53
You could write a book with the amount of information that's missing here. That's why the user forums exist and why the wiki, and release notes, point people to those user forums. We're coders, not documenters. That's not likely to change.

**Comment by francwalter** [comment] 2020-06-09 13:01
After all, is there an old version of PageEdit which works on Mac OS 10.11.6?
Which one then?

**Comment by dougmassay** [comment] 2020-06-09 13:11
There never was a version of PageEdit to work with 10.11.x to my knowledge. The build instructions for MacOS in the main README have always started with:

`export MACOSX_DEPLOYMENT_TARGET=10.12`

**Comment by eli-schwartz** [comment] 2020-06-09 13:31
The PageEdit project began on May 7, 2019 with commit f5c16d46211a62e76855bbb2932ccfe05295e0c7.

The Sigil project began on Aug 1, 2009 with commit https://github.com/Sigil-Ebook/Sigil/commit/a38dea92898064a1fd6d2d97b0bb7647cd929ecf.

There are far more old versions of Sigil than there are of PageEdit, and that's only to be expected. Naturally, old versions of a program will be compatible with the version of macOS that is its contemporary.

**Comment by francwalter** [comment] 2020-06-09 16:20
That why, now I understand. Thank!
